service: api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: codedpills
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: "*"

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello-test
          method: GET
          cors: true
  sendEmail:
    handler: sendEmail.sendEmailHandler
    events:
      - http:
          path: send-email
          method: POST
          cors: true
